
CREATE TABLESPACE BELSTAT 
       DATAFILE '/oradata/TEST1/belstat01.dbf' SIZE 100M AUTOEXTEND ON MAXSIZE 4096M
       EXTENT MANAGEMENT LOCAL AUTOALLOCATE
       SEGMENT SPACE MANAGEMENT AUTO
       FLASHBACK ON ;
