#!/bin/bash

export ORACLE_HOME=
export ORACLE_SID=TEST1
export NLS_LANG=American_America.UTF8
export PATH=$ORACLE_HOME/bin:$PATH

echo -n "Start operation " ; date

sqlplus bestat/qwe123rt <<EOF
set serveroutput on
exec DBMS_OUTPUT.ENABLE(2000000) ;

ALTER TABLE BESTAT.BESTAT_SQLAREA ENABLE ROW MOVEMENT ;
DELETE FROM BESTAT.BESTAT_SQLAREA WHERE POINT_ID in ( SELECT POINT_ID FROM BESTAT.BESTAT_COLLECTOR_POINTS cp WHERE STAMP_RECORD < SYSDATE - 7 ) ;
COMMIT ;
ALTER TABLE BESTAT.BESTAT_SQLAREA SHRINK SPACE CASCADE ;
ALTER TABLE BESTAT.BESTAT_SQLAREA DISABLE ROW MOVEMENT ;

ALTER TABLE BESTAT.BESTAT_DELTA_SQLAREA ENABLE ROW MOVEMENT ;
DELETE FROM BESTAT.BESTAT_DELTA_SQLAREA WHERE CR_POINT_ID in ( SELECT POINT_ID FROM BESTAT.BESTAT_COLLECTOR_POINTS cp WHERE STAMP_RECORD < SYSDATE - 7 ) ;
COMMIT ;
ALTER TABLE BESTAT.BESTAT_DELTA_SQLAREA SHRINK SPACE CASCADE ;
ALTER TABLE BESTAT.BESTAT_DELTA_SQLAREA DISABLE ROW MOVEMENT ;

ALTER TABLE BESTAT.BESTAT_V\$SQL_PLAN ENABLE ROW MOVEMENT ;
DELETE FROM BESTAT.BESTAT_V\$SQL_PLAN WHERE POINT_ID in ( SELECT POINT_ID FROM BESTAT.BESTAT_COLLECTOR_POINTS cp WHERE STAMP_RECORD < SYSDATE - 3 ) ;
COMMIT ;
ALTER TABLE BESTAT.BESTAT_V\$SQL_PLAN SHRINK SPACE CASCADE ;
ALTER TABLE BESTAT.BESTAT_V\$SQL_PLAN DISABLE ROW MOVEMENT ;

ALTER TABLE BESTAT.BESTAT_SESSION_STATS ENABLE ROW MOVEMENT ;
DELETE FROM BESTAT.BESTAT_SESSION_STATS WHERE POINT in ( SELECT POINT_ID FROM BESTAT.BESTAT_COLLECTOR_POINTS cp WHERE STAMP_RECORD < SYSDATE - 7 ) ;
COMMIT ;
ALTER TABLE BESTAT.BESTAT_SESSION_STATS SHRINK SPACE CASCADE ;
ALTER TABLE BESTAT.BESTAT_SESSION_STATS DISABLE ROW MOVEMENT ;

PURGE TABLESPACE SYSAUX ;
exit ;
EOF

echo -n "End operation " ; date
